-- Sequence for APP_USERS primary key
CREATE SEQUENCE APP_USERS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Main users table
CREATE TABLE APP_USERS (
  ID        NUMBER(19,0)   NOT NULL,
  USERNAME  VARCHAR2(100)  NOT NULL,
  PASSWORD  VARCHAR2(255)  NOT NULL,
  ROLE      VARCHAR2(50)   DEFAULT 'ROLE_USER' NOT NULL,
  CONSTRAINT PK_APP_USERS  PRIMARY KEY (ID),
  CONSTRAINT UQ_APP_USERS_USERNAME UNIQUE (USERNAME)
);

-- Default admin user  (bcrypt of "admin123")
INSERT INTO APP_USERS (ID, USERNAME, PASSWORD, ROLE) VALUES (
  APP_USERS_SEQ.NEXTVAL,
  'admin',
  '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
  'ROLE_ADMIN'
);

COMMIT;
